### ISSUE TITLE
Difference in model equations

### ISSUE THREAD

**Issue by teresacollins** [FDA/CiPA#4]
It seems that the github hergmod.c file contains different equations, than those published in Li et al 2018 (https://doi.org/10.1161/CIRCEP.116.004628), please see attached slides for details.  Could the authors please clarify the exact equations that should be used in model fitting.

Many Thanks

[github code vs Li et al 2018.pptx](https://github.com/FDA/CiPA/files/3984050/github.code.vs.Li.et.al.2018.pptx)

**Comment by bridder** [comment]
Hi theresacollins,

It is true they are written differently, but they are mathematically the same. Many of the sections you've highlighted are comparing terms of the form:

x^(k*y) versus exp(k*ln(x)*y)

Let's manipulate the right expression. In three steps, we can see it is identical to the left expression:

exp(k*ln(x)*y)
[exp(ln(x))]^(k*y)
x^(k*y)

In short, the equations look different because they are playing games with the rules of logarithms. I do not quite understand why such a roundabout way of writing the equations was chosen, but it doesn't matter.

Though perhaps I am overlooking something else. Please let me know if this doesn't answer your question or there is another discrepancy with the equations.

-Brad :)

**Comment by teresacollins** [comment]
Thanks Brad but I was interested in why some of the terms in the equations are negative when they should be positive, and vice versa,

Teresa

**Comment by bridder** [comment]
Hi Theresa, sorry I forgot about you.

I looked at the negative signs, and indeed they can be confusing, but try looking again. When I re-examined the equations, I noticed many negatives are nested inside parentheses multiplied by -1. The printed equations match the model equations.

Let me know if there are any more problems.

**Comment by bridder** [comment]
Hi, did my previous response fix the problem?
